### ISSUE TITLE
Credits and License

### ISSUE THREAD

**Issue by franglais125** [franglais125/apt-update-indicator#1]
Hi @RaphaelRochet !

I am trying to port this to be usable on apt-based distros (Debian, Ubuntu).
I have it working already locally...
I was just wondering how I should modify some files that are copyrighted with your name? What's the procedure for that?

Merci !

**Comment by RaphaelRochet** [comment]
Simply add a copyright line with year and your name in headers of all files that you modify.

**Comment by franglais125** [comment]
Thanks for the info!
