### ISSUE TITLE
Visual glitch when scrolling

### ISSUE THREAD

**Issue by lightonflux** [franglais125/apt-update-indicator#14]
Debian 9 with Gnome 3.22. Intel HD 4000 graphics. 

For some reason i can't screenshot it. The glitch disappears when making a screenshot. May be the focus change. 

https://vid.me/zQhs

If this is not caused by the extension please tell me who else to bother. :)

**Comment by franglais125** [comment]
Thanks a lot for your report!

I have actually experienced this myself very often when scrolling, quite annoying. Debian 9 with Gnome 3.22. Intel HD 3000 here.

I think this is some kind of upstream bug, with graphics not being properly updated. We probably need to file this upstream in the gnome bugzilla.

I have definitely seen this behavior in other applications like Synaptic and Rhythmbox, i.e. where long lists of entries are displayed.

**Comment by franglais125** [comment]
Well, I fixed the problem by removing some padding from stylesheet.css. I still think the bug is somewhere upstream, as simply adding some padding triggers the visual glitch...

Anyway, I'll upload the fix soon!

**Comment by franglais125** [comment]
I included a fix in master [32c77b1480aa8693382385d9bda4663d97fa29c8].

Do you mind testing it to check that if fixes the issue for you?

**Comment by lightonflux** [comment]
Works. Glitch is gone, but looks a bit weird without padding left and right.

![bildschirmfoto von 2017-06-30 13-58-13](https://user-images.githubusercontent.com/1377943/27734678-4b2034aa-5d9c-11e7-83b5-a2737bd39307.png)


Edit: Any idea how to tackle the upstream bug?

**Comment by franglais125** [comment]
I included a few other changes as well. Are you running the master branch or did you just cherry-picked that commit?

Here is what it looks for me (running master)

![screenshot from 2017-06-30 09-17-49](https://user-images.githubusercontent.com/19195975/27737204-4af512f6-5d75-11e7-84c4-accc43906c41.png)

As for the tackling the bug upstream, I tried to search for something similar in bugzilla.gnome.org, but couldn't find a duplicate. We can probably file a bug over there.
Too bad I don''t currently have a different graphics card to know if it's just intel.

**Comment by lightonflux** [comment]
Aha, i did not remove the old version before `make install`. Removed everything and ran it again, looks fine now.

**Comment by franglais125** [comment]
I just uploaded a new version to extensions.gnome.org. It will be available once it's reviewed! I'll close this issue now.

Thanks a lot for the report!

**Comment by lightonflux** [comment]
> I just uploaded a new version to extensions.gnome.org. 

Is that no 16? Because it has that glitch. (removed git version before installing from extensions.gnome.org).

**Comment by franglais125** [comment]
No, it's version 17. I uploaded it, but it takes a while before it's reviewed and available through extensions.gnome.org.

Meanwhile, you can install from git master :), and you'll see that it's version 17.

Don't forget to `git fetch` before running `make install`!

**Comment by franglais125** [comment]
If you are curious, here is the list of extensions pending review: https://extensions.gnome.org/review/
