### ISSUE TITLE
New in repository: Copy package name to clipboard when clicked

### ISSUE THREAD

**Issue by fi78** [franglais125/apt-update-indicator#17]
The feature "new in repository" is handy. But atm you need to type the package name to use it. Not perfect for packages with version numbers and or long names.

So it would be handy if you clicked on a package name that its name gets pasted into your clipboard.

**Comment by franglais125** [comment]
That's a very neat idea! Thanks for the suggestion. I'll try to see if I find time to do it. PRs welcome of course!

**Comment by fi78** [comment]
Here another extension that has this feature: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator

**Comment by franglais125** [comment]
Great, thanks! I'll paste here the link to the relevant function for future reference: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/master/extension.js#L225

**Comment by franglais125** [comment]
@fi78 I just added support for this, for all lists of packages (new in repository, updates, obsolete, etc).

Would you mind testing it?

**Comment by franglais125** [comment]
Here: [b9876a930d85a9c9b098cfeeda07390293966be4]. Loving this by the way!

**Comment by fi78** [comment]
Updated and tested. Works well. Did you change the entries to monospace as well?
