### ISSUE TITLE
Cannot apply updates

### ISSUE THREAD

**Issue by orschiro** [franglais125/apt-update-indicator#19]
Thank you for your extension!

When there are new updates, I click on "Apply Updates" but all it does is opening "Software" with the information that all software is up to date. 

I tested this on Ubuntu 17.10.

![image](https://user-images.githubusercontent.com/170947/32487050-cc807538-c3a8-11e7-97f4-4d7f9ecc5dc6.png)

![image](https://user-images.githubusercontent.com/170947/32487084-e6c5a526-c3a8-11e7-8b3a-81ea88dc0de9.png)

**Comment by franglais125** [comment]
You need to select your preferred update methid in the settings. I don't have my laptop now, but the options are something like:
- package updater
- software centre
- custom (and you can go to advanced mode and set a custom command)

Let me know how it goes!

**Comment by orschiro** [comment]
@franglais125 that was fast! Thanks so much. 

I think that will solve it. :-) 

If not, I will reopen it.
