### ISSUE TITLE
No icon when no updates are available

### ISSUE THREAD

**Issue by bdaase** [franglais125/apt-update-indicator#23]
I have set "Always show the indicator" to "true".  
Now, when there are no updates available, the tray icon is invisible, but I can properly click it, see

![Screenshot from 2019-04-05 21-46-59](https://user-images.githubusercontent.com/24682367/55652711-9ed26e00-57ec-11e9-99e2-5927914e21cb.png)

If there are updates, everything is fine, I have an icon and the correct number. 

OS: Ubuntu 19.04
DE: Gnome 3.32

**Comment by Etamuk** [comment]
I can confirm this. On my computer there is also no icon. Same as above.

OS: Ubuntu 19.04 (up to date)
DE: Gnome 3.32.1

**Comment by maksim-pinguin** [comment]
Same here

OS: Manjaro Linux 18.0.4 (up to date)
DE: Gnome 3.32.2

![Screenshot from 2019-07-22 04-55-33](https://user-images.githubusercontent.com/33628723/61603335-748eaa00-ac3d-11e9-9d5a-321cbdfc7097.png)

**Comment by HamburgerJungeJr** [comment]
I created a fork and fixed the problem.
https://extensions.gnome.org/extension/2197/new-apt-update-indicator/

**Comment by PHLAK** [comment]
Thanks @HamburgerJungeJr, any way you can PR this back to this repo?

**Comment by franglais125** [comment]
@HamburgerJungeJr thanks for the fork and mentioning :)

I don't have much time to maintain this, but would you mind pointing me to the fix so I can include it here?

Cheers!
Fran

**Comment by franglais125** [comment]
A new version was uploaded to extensions.gnome.org. Let me know whether the problem is still present. You can reopen this issue then.

**Comment by PHLAK** [comment]
This appears to be working correctly now.

![image](https://user-images.githubusercontent.com/53531/80035560-167d4480-84a5-11ea-8a92-d230f38fa94f.png)
