### ISSUE TITLE
Usage of object.actor is deprecated

### ISSUE THREAD

**Issue by TheSpartaPT** [franglais125/apt-update-indicator#25]
Your extension is spamming this issue title to the gnome-shell journal 
Check it like this: 
```bash
$ sudo journalctl /usr/bin/gnome-shell | grep -E 'apt-update-indicator|AptUpdateIndicator'
```

I fixed it by deleting the extension, cloning the repo, deleting all the references in your code to the property `.actor` everywhere and then installed it 

so for example on indicator.js:99 this:
```js 
this.actor.add_child(this.box);
``` 
became this: 
```js
this.add_child(this.box);
```

seems to have fixed it, idk if that's the best or the only solution to the problem, I won't PR it because I didn't bother to check if what I was doing was right so I might have created more issues in the process, although it seems to be working as intended.

**Comment by TheSpartaPT** [comment]
forgot to mention, I'm on gnome-shell v3.34.1

**Comment by franglais125** [comment]
Indeed, I need to update the extension to support newer version of Gnome! Hopefully I can try this in the next few weeks/months. Patches welcome.

**Comment by franglais125** [comment]
Fixed on v21. Uploaded to extensions.gnome.org. Cheers!
