### ISSUE TITLE
Lock screen issue

### ISSUE THREAD

**Issue by mohegan** [franglais125/apt-update-indicator#27]
With the app-update-indictator enabled, the lock screen in gnome-shell doesn't work correctly. The screen doesn't switch off and I can't connect to unlock the screen (no user icon in the lock screen).
If I disabled the extension, the lock screen works well.

I have a netbook computer with an external screen.

**Comment by franglais125** [comment]
Hmm, perhaps this is an incompatibility with newer version of Gnome. I need to port the extension to anything above 3.30. What version are you running?

**Comment by mohegan** [comment]
It works now with gnome 3.36 but I have a bug with the default icon. I have a red icon instead of a software icon (see the attach file). The others icons work great (actualisation, updates available).

You use "apt-update-indicator-symbolic" but I can't find this icon (in /usr/share/icons/Adwaita). I think the replacement icon is "system-software-install-symbolic". I change manually the indicator.js file but it doesn't work.

![Capture d’écran du 2020-04-20 14-25-34](https://user-images.githubusercontent.com/635456/79751420-d7b78500-8312-11ea-9e97-e48f651b310c.png)

**Comment by franglais125** [comment]
What version are you using? If you have it running on 3.36, I assume you are installing from `git`, in which case the icon the extension uses is actually `package-x-generic-symbolic`.

Would you mind perhaps running the latest git code?

**Comment by mohegan** [comment]
I have tested the git repository and every is fine. Maybe, you can update your extension in extensions.gnome.org

Good Job !

**Comment by franglais125** [comment]
v21 was posted yesterday. Cheers!

**Comment by mohegan** [comment]
Thanks. It works great !
