### ISSUE TITLE
Icons set does not comply with Gnome guidelines

### ISSUE THREAD

**Issue by lucatrv** [franglais125/apt-update-indicator#4]
Hi, it would be nice to refine the icons set in order to improve compliance with the Gnome guidelines (see in particular "Color vs. symbolic icons"):
[https://developer.gnome.org/hig/stable/icons-and-artwork.html.en](https://developer.gnome.org/hig/stable/icons-and-artwork.html.en)

IMHO the status and sync icons should be "symbolic", while the updates notification icon could be kept colored to better stand out.

This would be a good option for the sync icon (part of the "gnome-icon-theme-symbolic" package):
/usr/share/icons/gnome/scalable/emblems/emblem-synchronizing-symbolic.svg

As for updates notification, the current icon is already nice, but this would be another good option (part of the "gnome-icon-theme-symbolic" package):
/usr/share/icons/gnome/scalable/status/software-update-urgent-symbolic.svg

Then it would be useful to distinguish between regular and security updates. In this case I would consider the following two options instead (part of the "gnome-icon-theme" package):
/usr/share/icons/gnome/32x32/status/software-update-available.png
/usr/share/icons/gnome/32x32/status/software-update-urgent.png

Note: I would not use the icon "/usr/share/icons/gnome/scalable/status/software-update-available-symbolic.svg" for regular updates, as it does not stand out enough.

Finally for the status icon, this would be a good option IMHO (part of the "gnome-icon-theme-symbolic" package):
/usr/share/icons/gnome/scalable/apps/system-software-install-symbolic.svg

Otherwise here are a couple of other options outside Gnome:
[https://thenounproject.com/term/open-source/35033/](https://thenounproject.com/term/open-source/35033/)
[https://www.iconfinder.com/search/?q=package&style=glyph&price=free](https://www.iconfinder.com/search/?q=package&style=glyph&price=free)

Cheers

**Comment by franglais125** [comment]
That's a nice set of suggestions!

I'll look into this as well. I'm travelling at the moment, so it might take some time.

Thanks for your attention to details!

**Comment by franglais125** [comment]
I think this is fixed in [2aceb9ee5523fcc7554c28a6bbb7fefabe07bd52]. The indicator now makes use of symbolic icons, except when there are updates available (so that it is more obvious that the user's attention is required).

I opened a new issue #6 for implementing the distinction between regular/urgent updates.

Thanks for your contribution!
