### ISSUE TITLE
Larger symbolic icon

### ISSUE THREAD

**Issue by franglais125** [franglais125/apt-update-indicator#8]
@lucatrv: thanks for your input.

It'd be nice to have an icon that is:
1) a bit larger
2) nicer

Tentative solution for 1)
https://github.com/franglais125/apt-update-indicator/tree/larger_icon

**Comment by franglais125** [comment]
@lucatrv I found an easy fix for this... It's again int he reorganization branch.

Let me know what you think!

**Comment by lucatrv** [comment]
The icon size looks good to me now

**Comment by lucatrv** [comment]
Hi, I noticed that the icon size is affected by the Fonts Scaling Factor (set in the Gnome Tweak Tool). On my PC I usually set it to 1.25, and the icon size looks good. However it is too big if I set the scaling factor to 1.0, or too small if I set it to 1.5. Looking at the code, I noticed the following line:
`iconSize = scaleFactor > 0 ? Math.round((iconSize) / scaleFactor) : iconSize;`
and thought that it is should be:
`iconSize = scaleFactor > 0 ? Math.round((iconSize) * scaleFactor) : iconSize;`
I changed it, but the icon size remains the same, so it seems that the scaling code is not working correctly on my PC...

**Comment by franglais125** [comment]
Hi! Thanks for pointing out the Font scaling...

The code that you see there is actually for the HiDPI scale factor, the one you find in the "Windows" section of the Tweak tool.

I'll look into what you reported, as if someone is using the font scaling, the indicator will (again) look small.

**Comment by franglais125** [comment]
I finally ended up reverting the larger icon size I was setting manually, and I now merged the branch with our own svg file, which is naturally bigger. Scaling should now work properly again.

I'll close this issue now!
